name: dbtvault_greenplum_demo
profile: dbtvault_greenplum_demo
version: '5.1.0'
require-dbt-version: ['>=0.18.0', '<0.20.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
data-paths:
  - data
macro-paths:
  - macros
source-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: '1992-01-11'
  tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  dbtvault_greenplum_demo:
    raw_stage:
      tags:
        - 'raw'
      materialized: view
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: table
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'
    vault:
      tags:
        - 'vault'
      bridges:
        materialized: bridge_incremental
        tags:
          - 'bridges'
      pits:
        materialized: pit_incremental
        tags:
          - 'pits'

# path to compiled .sql files
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"