config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

dbtvault_greenplum_demo:
  outputs:
    dev:
      type: postgres
      threads: 2
      host: rc1c-59ve9h880cqf2t4d.mdb.yandexcloud.net
      port: 5432
      user: otus
      pass: Qwerty123
      dbname: postgres
      schema: public
  target: dev